//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace R2kDemo {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SimpChinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimpChinese() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R2kDemo.SimpChinese", typeof(SimpChinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 相邻判别时间的有效值是0－255 的本地化字符串。
        /// </summary>
        internal static string stMsgNJValid {
            get {
                return ResourceManager.GetString("stMsgNJValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        internal static string strBtnClearEditData {
            get {
                return ResourceManager.GetString("strBtnClearEditData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string strBtnClearListView {
            get {
                return ResourceManager.GetString("strBtnClearListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        internal static string strBtnConnect {
            get {
                return ResourceManager.GetString("strBtnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认参数 的本地化字符串。
        /// </summary>
        internal static string strBtnDefaultParams {
            get {
                return ResourceManager.GetString("strBtnDefaultParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开 的本地化字符串。
        /// </summary>
        internal static string strBtnDisconnect {
            get {
                return ResourceManager.GetString("strBtnDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        internal static string strBtnGetAnts {
            get {
                return ResourceManager.GetString("strBtnGetAnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        internal static string strBtnGetDI {
            get {
                return ResourceManager.GetString("strBtnGetDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销毁标签 的本地化字符串。
        /// </summary>
        internal static string strBtnKillTag {
            get {
                return ResourceManager.GetString("strBtnKillTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑设备 的本地化字符串。
        /// </summary>
        internal static string strBtnModifyDev {
            get {
                return ResourceManager.GetString("strBtnModifyDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 的本地化字符串。
        /// </summary>
        internal static string strBtnPerform {
            get {
                return ResourceManager.GetString("strBtnPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寻卡一次 的本地化字符串。
        /// </summary>
        internal static string strBtnReadOnce {
            get {
                return ResourceManager.GetString("strBtnReadOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 的本地化字符串。
        /// </summary>
        internal static string strBtnReadTagData {
            get {
                return ResourceManager.GetString("strBtnReadTagData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索设备 的本地化字符串。
        /// </summary>
        internal static string strBtnSearchDev {
            get {
                return ResourceManager.GetString("strBtnSearchDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string strBtnSetAlive {
            get {
                return ResourceManager.GetString("strBtnSetAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string strBtnSetAnts {
            get {
                return ResourceManager.GetString("strBtnSetAnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string strBtnSetDevNo {
            get {
                return ResourceManager.GetString("strBtnSetDevNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string strBtnSetDO {
            get {
                return ResourceManager.GetString("strBtnSetDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string strBtnSetNeighJudge {
            get {
                return ResourceManager.GetString("strBtnSetNeighJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置参数 的本地化字符串。
        /// </summary>
        internal static string strBtnSetParams {
            get {
                return ResourceManager.GetString("strBtnSetParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续读卡 的本地化字符串。
        /// </summary>
        internal static string strBtnStartReadData {
            get {
                return ResourceManager.GetString("strBtnStartReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string strBtnStopReadData {
            get {
                return ResourceManager.GetString("strBtnStopReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string strBtnUpdate {
            get {
                return ResourceManager.GetString("strBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入 的本地化字符串。
        /// </summary>
        internal static string strBtnWriteTagData {
            get {
                return ResourceManager.GetString("strBtnWriteTagData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1号 的本地化字符串。
        /// </summary>
        internal static string strCbAnt1 {
            get {
                return ResourceManager.GetString("strCbAnt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2号 的本地化字符串。
        /// </summary>
        internal static string strCbAnt2 {
            get {
                return ResourceManager.GetString("strCbAnt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3号 的本地化字符串。
        /// </summary>
        internal static string strCbAnt3 {
            get {
                return ResourceManager.GetString("strCbAnt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4号 的本地化字符串。
        /// </summary>
        internal static string strCbAnt4 {
            get {
                return ResourceManager.GetString("strCbAnt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入口1 的本地化字符串。
        /// </summary>
        internal static string strCbIn1 {
            get {
                return ResourceManager.GetString("strCbIn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入口2 的本地化字符串。
        /// </summary>
        internal static string strCbIn2 {
            get {
                return ResourceManager.GetString("strCbIn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出口1 的本地化字符串。
        /// </summary>
        internal static string strCbOut1 {
            get {
                return ResourceManager.GetString("strCbOut1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出口2 的本地化字符串。
        /// </summary>
        internal static string strCbOut2 {
            get {
                return ResourceManager.GetString("strCbOut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为文件 的本地化字符串。
        /// </summary>
        internal static string strCbSaveFile {
            get {
                return ResourceManager.GetString("strCbSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天线参数 的本地化字符串。
        /// </summary>
        internal static string strGbAntParams {
            get {
                return ResourceManager.GetString("strGbAntParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信方式 的本地化字符串。
        /// </summary>
        internal static string strGbCommMode {
            get {
                return ResourceManager.GetString("strGbCommMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销毁标签 的本地化字符串。
        /// </summary>
        internal static string strGbDestroyTag {
            get {
                return ResourceManager.GetString("strGbDestroyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备参数 的本地化字符串。
        /// </summary>
        internal static string strGbDevParams {
            get {
                return ResourceManager.GetString("strGbDevParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IO操作 的本地化字符串。
        /// </summary>
        internal static string strGbIOOpr {
            get {
                return ResourceManager.GetString("strGbIOOpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁卡/解锁 的本地化字符串。
        /// </summary>
        internal static string strGbLockTag {
            get {
                return ResourceManager.GetString("strGbLockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络参数 的本地化字符串。
        /// </summary>
        internal static string strGbNetParams {
            get {
                return ResourceManager.GetString("strGbNetParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读/写数据 的本地化字符串。
        /// </summary>
        internal static string strGbRWData {
            get {
                return ResourceManager.GetString("strGbRWData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口参数 的本地化字符串。
        /// </summary>
        internal static string strGbSPParams {
            get {
                return ResourceManager.GetString("strGbSPParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久不可写 的本地化字符串。
        /// </summary>
        internal static string strItemPerUnwritable {
            get {
                return ResourceManager.GetString("strItemPerUnwritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 永久可写 的本地化字符串。
        /// </summary>
        internal static string strItemPerWritable {
            get {
                return ResourceManager.GetString("strItemPerWritable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全锁定 的本地化字符串。
        /// </summary>
        internal static string strItemSecuLock {
            get {
                return ResourceManager.GetString("strItemSecuLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解锁 的本地化字符串。
        /// </summary>
        internal static string strItemUnLock {
            get {
                return ResourceManager.GetString("strItemUnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心跳时间 的本地化字符串。
        /// </summary>
        internal static string strLabAlive {
            get {
                return ResourceManager.GetString("strLabAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毫秒     1/10dbm 的本地化字符串。
        /// </summary>
        internal static string strLabAntUnit {
            get {
                return ResourceManager.GetString("strLabAntUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波特率 的本地化字符串。
        /// </summary>
        internal static string strLabBaudRate {
            get {
                return ResourceManager.GetString("strLabBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验位 的本地化字符串。
        /// </summary>
        internal static string strLabCheckBits {
            get {
                return ResourceManager.GetString("strLabCheckBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string strLabCommPort {
            get {
                return ResourceManager.GetString("strLabCommPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取次数： 的本地化字符串。
        /// </summary>
        internal static string strLabCount {
            get {
                return ResourceManager.GetString("strLabCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据位 的本地化字符串。
        /// </summary>
        internal static string strLabDataBits {
            get {
                return ResourceManager.GetString("strLabDataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的IP 的本地化字符串。
        /// </summary>
        internal static string strLabDestIP {
            get {
                return ResourceManager.GetString("strLabDestIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目的端口 的本地化字符串。
        /// </summary>
        internal static string strLabDestPort {
            get {
                return ResourceManager.GetString("strLabDestPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灭活密码 的本地化字符串。
        /// </summary>
        internal static string strLabDestrlyPwd {
            get {
                return ResourceManager.GetString("strLabDestrlyPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问密码 的本地化字符串。
        /// </summary>
        internal static string strLabDestroyAccessPwd {
            get {
                return ResourceManager.GetString("strLabDestroyAccessPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号 的本地化字符串。
        /// </summary>
        internal static string strLabDevNo {
            get {
                return ResourceManager.GetString("strLabDevNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网关 的本地化字符串。
        /// </summary>
        internal static string strLabGateway {
            get {
                return ResourceManager.GetString("strLabGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        internal static string strLabIPAdd {
            get {
                return ResourceManager.GetString("strLabIPAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP模式 的本地化字符串。
        /// </summary>
        internal static string strLabIPMode {
            get {
                return ResourceManager.GetString("strLabIPMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        internal static string strLabLength {
            get {
                return ResourceManager.GetString("strLabLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问密码 的本地化字符串。
        /// </summary>
        internal static string strLabLockAccessPwd {
            get {
                return ResourceManager.GetString("strLabLockAccessPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作区域 的本地化字符串。
        /// </summary>
        internal static string strLabLockBank {
            get {
                return ResourceManager.GetString("strLabLockBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作类型 的本地化字符串。
        /// </summary>
        internal static string strLabLockType {
            get {
                return ResourceManager.GetString("strLabLockType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子网掩码 的本地化字符串。
        /// </summary>
        internal static string strLabMask {
            get {
                return ResourceManager.GetString("strLabMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相邻判别 的本地化字符串。
        /// </summary>
        internal static string strLabNeighJudge {
            get {
                return ResourceManager.GetString("strLabNeighJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络模式 的本地化字符串。
        /// </summary>
        internal static string strLabNetMode {
            get {
                return ResourceManager.GetString("strLabNetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string strLabPort {
            get {
                return ResourceManager.GetString("strLabPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下设置仅适用于TCP客户端模式： 的本地化字符串。
        /// </summary>
        internal static string strLabPromotion {
            get {
                return ResourceManager.GetString("strLabPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问密码 的本地化字符串。
        /// </summary>
        internal static string strLabRWAccessPwd {
            get {
                return ResourceManager.GetString("strLabRWAccessPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作区域 的本地化字符串。
        /// </summary>
        internal static string strLabRWBank {
            get {
                return ResourceManager.GetString("strLabRWBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据 的本地化字符串。
        /// </summary>
        internal static string strLabRWData {
            get {
                return ResourceManager.GetString("strLabRWData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始地址 的本地化字符串。
        /// </summary>
        internal static string strLabStartAdd {
            get {
                return ResourceManager.GetString("strLabStartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签数： 的本地化字符串。
        /// </summary>
        internal static string strLabTagCount {
            get {
                return ResourceManager.GetString("strLabTagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天线号 的本地化字符串。
        /// </summary>
        internal static string strLvHeadAntNo {
            get {
                return ResourceManager.GetString("strLvHeadAntNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次数 的本地化字符串。
        /// </summary>
        internal static string strLvHeadCount {
            get {
                return ResourceManager.GetString("strLvHeadCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号 的本地化字符串。
        /// </summary>
        internal static string strLvHeadDevNo {
            get {
                return ResourceManager.GetString("strLvHeadDevNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EPC 的本地化字符串。
        /// </summary>
        internal static string strLvHeadEPC {
            get {
                return ResourceManager.GetString("strLvHeadEPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string strLvHeadNo {
            get {
                return ResourceManager.GetString("strLvHeadNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心跳时间不能为空 的本地化字符串。
        /// </summary>
        internal static string strMsgAliveNotEmpty {
            get {
                return ResourceManager.GetString("strMsgAliveNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心跳时间的有效值是0－255 的本地化字符串。
        /// </summary>
        internal static string strMsgAliveValid {
            get {
                return ResourceManager.GetString("strMsgAliveValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        internal static string strMsgConnectFailure {
            get {
                return ResourceManager.GetString("strMsgConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号不能为空 的本地化字符串。
        /// </summary>
        internal static string strMsgDevNoNotEmpty {
            get {
                return ResourceManager.GetString("strMsgDevNoNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号的有效值是0－255 的本地化字符串。
        /// </summary>
        internal static string strMsgDevNoValid {
            get {
                return ResourceManager.GetString("strMsgDevNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销毁失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedDes {
            get {
                return ResourceManager.GetString("strMsgFailedDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取天线参数失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedGetAnt {
            get {
                return ResourceManager.GetString("strMsgFailedGetAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取输入口状态失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedGetIn {
            get {
                return ResourceManager.GetString("strMsgFailedGetIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedOpr {
            get {
                return ResourceManager.GetString("strMsgFailedOpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读数据失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedReadData {
            get {
                return ResourceManager.GetString("strMsgFailedReadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心跳时间设置失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedSetAlive {
            get {
                return ResourceManager.GetString("strMsgFailedSetAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置天线参数失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedSetAnt {
            get {
                return ResourceManager.GetString("strMsgFailedSetAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信参数设置失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedSetCommParam {
            get {
                return ResourceManager.GetString("strMsgFailedSetCommParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号设置失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedSetDevNo {
            get {
                return ResourceManager.GetString("strMsgFailedSetDevNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相邻判别时间设置失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedSetNJ {
            get {
                return ResourceManager.GetString("strMsgFailedSetNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出口设置失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedSetOut {
            get {
                return ResourceManager.GetString("strMsgFailedSetOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入失败 的本地化字符串。
        /// </summary>
        internal static string strMsgFailedWrite {
            get {
                return ResourceManager.GetString("strMsgFailedWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化失败 的本地化字符串。
        /// </summary>
        internal static string strMsgInitFailure {
            get {
                return ResourceManager.GetString("strMsgInitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的IP地址 的本地化字符串。
        /// </summary>
        internal static string strMsgInvalidIPAdd {
            get {
                return ResourceManager.GetString("strMsgInvalidIPAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的端口号 的本地化字符串。
        /// </summary>
        internal static string strMsgInvalidPort {
            get {
                return ResourceManager.GetString("strMsgInvalidPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际数据长度和指定的长度不同 的本地化字符串。
        /// </summary>
        internal static string strMsgLengthDiff {
            get {
                return ResourceManager.GetString("strMsgLengthDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相邻判别时间不能为空 的本地化字符串。
        /// </summary>
        internal static string strMsgNJNotEmpty {
            get {
                return ResourceManager.GetString("strMsgNJNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 含有非数字字符 的本地化字符串。
        /// </summary>
        internal static string strMsgNotDigit {
            get {
                return ResourceManager.GetString("strMsgNotDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功率有效值为200－300 的本地化字符串。
        /// </summary>
        internal static string strMsgPowerValid {
            get {
                return ResourceManager.GetString("strMsgPowerValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码中含有0－9，A－F之外的非法字符 的本地化字符串。
        /// </summary>
        internal static string strMsgPwdInvalidChar {
            get {
                return ResourceManager.GetString("strMsgPwdInvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码必须为8位 的本地化字符串。
        /// </summary>
        internal static string strMsgPwdMustEight {
            get {
                return ResourceManager.GetString("strMsgPwdMustEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择要操作的区域 的本地化字符串。
        /// </summary>
        internal static string strMsgSelecOprBank {
            get {
                return ResourceManager.GetString("strMsgSelecOprBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的波特率 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectBaudRate {
            get {
                return ResourceManager.GetString("strMsgSelectBaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择数据位 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectDataBits {
            get {
                return ResourceManager.GetString("strMsgSelectDataBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择IP地址模式 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectIPMode {
            get {
                return ResourceManager.GetString("strMsgSelectIPMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择有效长度 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectLength {
            get {
                return ResourceManager.GetString("strMsgSelectLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择网络模式 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectNetMode {
            get {
                return ResourceManager.GetString("strMsgSelectNetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择操作类型 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectOprType {
            get {
                return ResourceManager.GetString("strMsgSelectOprType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择校验方式 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectParity {
            get {
                return ResourceManager.GetString("strMsgSelectParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择正确的端口号 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectPort {
            get {
                return ResourceManager.GetString("strMsgSelectPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择读写区域 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectRWBank {
            get {
                return ResourceManager.GetString("strMsgSelectRWBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择起始地址 的本地化字符串。
        /// </summary>
        internal static string strMsgSelectStartAdd {
            get {
                return ResourceManager.GetString("strMsgSelectStartAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销毁成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedDes {
            get {
                return ResourceManager.GetString("strMsgSucceedDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取天线参数成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedGetAnt {
            get {
                return ResourceManager.GetString("strMsgSucceedGetAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedOpr {
            get {
                return ResourceManager.GetString("strMsgSucceedOpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 心跳时间设置成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedSetAlive {
            get {
                return ResourceManager.GetString("strMsgSucceedSetAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置天线参数成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedSetAnt {
            get {
                return ResourceManager.GetString("strMsgSucceedSetAnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信参数设置成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedSetCommParam {
            get {
                return ResourceManager.GetString("strMsgSucceedSetCommParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备号设置成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedSetDevNo {
            get {
                return ResourceManager.GetString("strMsgSucceedSetDevNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相邻判别时间设置成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedSetNJ {
            get {
                return ResourceManager.GetString("strMsgSucceedSetNJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出口设置成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedSetOut {
            get {
                return ResourceManager.GetString("strMsgSucceedSetOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入成功 的本地化字符串。
        /// </summary>
        internal static string strMsgSucceedWrite {
            get {
                return ResourceManager.GetString("strMsgSucceedWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寻卡时间有效值为100－10000 的本地化字符串。
        /// </summary>
        internal static string strMsgValidWT {
            get {
                return ResourceManager.GetString("strMsgValidWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        internal static string strRbAsc {
            get {
                return ResourceManager.GetString("strRbAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        internal static string strRbDesc {
            get {
                return ResourceManager.GetString("strRbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络 的本地化字符串。
        /// </summary>
        internal static string strRbNet {
            get {
                return ResourceManager.GetString("strRbNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 串口 的本地化字符串。
        /// </summary>
        internal static string strRbSerialPort {
            get {
                return ResourceManager.GetString("strRbSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本操作 的本地化字符串。
        /// </summary>
        internal static string strTpGeneral {
            get {
                return ResourceManager.GetString("strTpGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信参数设置 的本地化字符串。
        /// </summary>
        internal static string strTpSetCommParam {
            get {
                return ResourceManager.GetString("strTpSetCommParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读写器参数设置 的本地化字符串。
        /// </summary>
        internal static string strTpSetReaderParam {
            get {
                return ResourceManager.GetString("strTpSetReaderParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签读写 的本地化字符串。
        /// </summary>
        internal static string strTpTagAccess {
            get {
                return ResourceManager.GetString("strTpTagAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        internal static string strZlHeadIP {
            get {
                return ResourceManager.GetString("strZlHeadIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MAC 的本地化字符串。
        /// </summary>
        internal static string strZlHeadMAC {
            get {
                return ResourceManager.GetString("strZlHeadMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string strZlHeadNo {
            get {
                return ResourceManager.GetString("strZlHeadNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string strZlHeadPort {
            get {
                return ResourceManager.GetString("strZlHeadPort", resourceCulture);
            }
        }
    }
}
